# idioms_db.py — dictionary of idioms and meanings
idioms = {
    "A big cheese": "an important or a powerful person in a group or family",
    "A bird’s eye view": "a view from a very high place which allows you to see a large area",
    "A bone of contention": "something that people argue for a long time",
    "A cock and a bull story": "a story or an explanation which is obviously not true",
    "At the crack of the dawn": "very early in morning",
    "A cuckoo in the nest": "someone in a group of people but not liked by them",
    "A litmus test": "a method which clearly proves something",
    "As the crow flies": "measuring distance between two places in a straight line",
    "A dead letter": "an argument or law not followed by anyone",
    "At the drop of the hat": "you do something easily and without any preparation",
    "An early bird": "someone who gets up early in the morning",
    "An educated guess": "a guess which was likely to get corrected",
    "At the eleventh hour": "be too late",
    "A queer fish": "a strange person",
    "A wakeup call": "an event done to warn someone",
    "A worm’s eye view": "having very little knowledge about something",
    "A witch hunt": "an attempt to find and punish those who have options that are believed to be dangerous",
    "At the heels of": "to follow someone",
    "A dish fit for Gods": "something of very high quality",
    "A game of two equal halves": "a sudden change in circumstances",
    "Afraid of one’s own shadow": "to become easily frightened",
    "Against the clock": "to be in a hurry to do something before a particular time",
    "Air one’s dirty laundry": "to make public something embarrassing that should be kept secret",
    "All systems go": "everything is ready",
    "An arm and a leg": "a large amount of money",
    "Appear out of nowhere": "to appear suddenly without warning",
    "Apple of someone’s eye": "someone loved very much",
    "Ask for the moon": "to ask for too much",
    "Asleep at the switch": "not to be alert on opportunity",
    "At sixes and sevens": "to be lost and bewildered",
    "At someone’s beck and call": "to be always ready to serve",
    "At the bottom of the ladder": "at the lowest level",
    "A house of cards": "a poor plan",
    "At an arm’s length": "to keep at a distance",
    "A boon in disguise": "a benefit in loss",
    "A bull in a China shop": "an awkward person",
    "A red letter day": "an important day",
    "A nine days wonder": "pleasure for a short time",
    "A bit under the weather": "falling ill",
    "Bad blood": "feelings of hate between two families",
    "Bend your ears": "to talk to someone for a very long time about something boring",
    "Bite your tongue": "to stop yourself from saying something because it would be better not to",
    "Black and blue": "full of bruises",
    "Blue blood": "belonging to high social class",
    "Be above board": "to be honest and legal",
    "Be bouncing off the walls": "excited and full of nervous energy",
    "Bow and scrap": "try too hard to please someone in a position of authority",
    "Brass monkey weather": "extremely cold weather",
    "Be tailor made": "to be completely suitable for someone",
    "Break the ice": "to make more comfort or relaxed with a person whom you have not met earlier, to break the silence",
    "Be as clear as mud": "to be impossible to understand",
    "Be on cloud nine": "be very happy",
    "Between the devil and deep blue sea": "a situation where you must choose between two equally unpleasant options",
    "Be in the doldrums": "not very successful or nothing new is taking place",
    "Beat the drum": "to speak eagerly about something you support",
    "Be on the edge": "to be nervous or worried about something",
    "Be in seventh heaven": "extremely happy",
    "Be at each other’s throat": "two persons arguing angrily",
    "Batten down the hatches": "to prepare for trouble",
    "Back the wrong horse": "to support someone weak",
    "Back to square one": "to reach again to the starting point",
    "Back to the salt mines": "back to something that you don’t want to do",
    "Ball of fire": "active and energetic",
    "Beat one’s head against the wall": "to try to do something that is hopeless",
    "Bark up the wrong tree": "to make a wrong assumption",
    "Beat one’s brain out": "to work hard",
    "Begin to see the light": "to begin to understand",
    "Behind closed doors": "done in secret",
    "Bet on the wrong horse": "to misread the future",
    "Bent on doing": "to be determined to do something",
    "Bite off more than one can chew": "to attempt more than one can handle",
    "Bite the bullet": "to face a difficult situation bravely",
    "Bitter pill to swallow": "an unpleasant fact that must be accepted",
    "Black sheep of the family": "worst member",
    "Blessing in disguise": "something that turns out to be good which earlier appeared to be wrong",
    "Blind leading the blind": "someone who does not understand something but tries to explain it to other",
    "Blow one’s own horn": "to praise one",
    "Blow someone’s mind": "excite someone",
    "Bring home the bacon": "to earn money to live",
    "Blue in the face": "exhausted and speechless",
    "Break the back of": "reduce the power of something",
    "Burn a hole in one’s pocket": "to spend money quickly",
    "Burn the midnight oil": "to study till late of night",
    "Bushman’s holiday": "a holiday where you spend doing same thing as you did at working days",
    "Button’s one lip": "to keep quiet",
    "Break a leg": "to wish good luck",
    "Carrot and sticks": "You use both awards as well as punishments to make someone do something",
    "Cloak and dragger": "when people behave in a very secret manner",
    "Cards are stacked against": "luck is against you",
    "Crack a book": "to open book to study",
    "Cross a bridge before one comes to it": "worry about the future in advance",
    "Carry coals to new castle": "to take something to a place or a person that has a lot of that thing already",
    "Cast in the same mould": "to be very similar",
    "Change horses in midstream": "to change plans",
    "Cap it all": "to finish",
    "Cried with eyes out": "cried a lot",
    "Carry the can": "you take the blame for something, even though you didn't do it or are only partly at fault",
    "Cast a long shadow": "someone that has considerable influence on other people or events",
    "Cat and dog life": "If people lead a cat and dog life, they are always arguing",
    "Drive a wedge between": "to break relationship between the two",
    "Dances to the tune": "to always do what someone tells you to do",
    "Dressed up to the nines": "wearing fancy clothes",
    "Dragging its feet": "delaying in decision, not showing enthusiasm",
    "Davey Jones' locker": "the bottom of the sea or resting place of drowned sailors",
    "Dancing on someone's grave": "you will outlive or outlast them and celebrate their demise",
    "Dog in the manger": "they don't want others to enjoy what they cannot use",
    "Don't cry over spilt milk": "don't worry about things that can't be changed",
    "Don't wash your dirty laundry in public": "don't argue or disclose personal problems publicly",
    "Donkey work": "any hard, boring work or task",
    "Don't throw bricks when you live in a glass house": "don't be a hypocrite",
    "Entering the 80th orbit": "celebrating the 80th birthday",
    "Eleventh hour decision": "decision that is made at the last possible minute",
    "End in smoke": "to bear no result",
    "Earth shattering": "not at all surprising",
    "Eat humble pie": "to apologize humbly",
    "Elephant in the room": "a big problem everyone knows but avoids discussing",
    "Egg on your face": "to look foolish or embarrassed",
    "Eye for an eye": "retributive justice",
    "Eyes are bigger than one's stomach": "to be greedy or overambitious",
    "From cradle to grave": "during the whole span of your life",
    "Face the music": "to accept punishment for something you have done",
    "Feel the pinch": "to have problems with money",
    "Fall on your own sword": "to be cheated by someone you trust",
    "Feather in one’s cap": "something that you achieve and are proud of",
    "Firing on all cylinders": "working at full efficiency",
    "French leave": "to leave a gathering without saying goodbye or without permission",
    "Fall on our feet": "to succeed in doing something where there was a risk of failure",
    "Fall on your sword": "to resign or accept the consequences of what one has done wrong",
    "Fingers and thumbs": "being clumsy and not very skilled with one's hands",
    "Finger in the pie": "to have an interest or involvement in something",
    "Flash in the pan": "something very noticeable but short-lived",
    "Follow your nose": "go straight ahead (used when giving directions)",
    "Fool's paradise": "a false sense of happiness or success",
    "Foot in mouth": "to say something embarrassing, inappropriate, or stupid",
    "For a song": "to buy or sell something very cheaply",
    "For donkey's years": "to do something for a very long time without much change",
    "Get off the hook": "to be freed from all obligations",
    "Give up the ghost": "to die",
    "Got the slap on the wrist": "to receive a light punishment",
    "Give someone a bird": "to make fun of someone",
    "Got the wind up": "to be scared",
    "Get a raw deal": "to not be treated fairly",
    "Gift of the gab": "the talent of speaking persuasively",
    "Gives cold shoulder": "to ignore someone",
    "Get your wires crossed": "to misunderstand someone, especially in arrangements",
    "Give me five": "a gesture of greeting or congratulation by slapping hands",
    "Give me a hand": "to help someone",
    "Give someone a piece of your mind": "to criticize someone strongly and angrily",
    "Go bananas": "to go wild with excitement, anxiety, or worry",
    "Go tell it to birds": "used when someone says something not credible or false",
    "Go under the hammer": "to be sold at an auction",
    "Graveyard shift": "a very late night work shift",
    "Grease monkey": "an idiomatic term for a mechanic",
    "Have ants in your pants": "to be unable to keep still due to excitement or worry",
    "Having a whole of a time": "to enjoy something very much",
    "Hold one’s horse": "to be patient",
    "Have a big mouth": "to gossip or reveal secrets",
    "Himalayan blunder": "a serious mistake",
    "Have a one track mind": "to think only about one thing",
    "Have clean hands": "to be guiltless",
    "Have an egg on the face": "to be embarrassed",
    "Have eyes bigger than stomach": "to desire more food than one can eat",
    "Heart missed a beat": "to be very excited or startled",
    "Heart in the right place": "to be good-natured",
    "Hit the nail on the head": "to do something exactly right",
    "Hand to mouth": "to live with barely enough money for basic needs",
    "Have no truck with": "to refuse to be involved with someone or something",
    "Hit the bull's-eye": "to be exactly right or achieve the best result",
    "Hold water": "to be logically sound or valid",
    "Hornets' nest": "a situation full of trouble or dispute",
    "In dribs and drabs": "in small amounts at a time",
    "In black and white": "to be given in writing",
    "In the blues": "to be low spirited",
    "In cahoots with": "to be in a secret partnership, usually dishonest",
    "If the shoe fits": "used to suggest that something applies to a person if it describes them accurately",
    "Jumping Judas!": "An expression of surprise or shock.",
    "Jungle out there": "The situation is dangerous and there are no rules.",
    "Jury's out": "There is no general agreement or consensus on an issue.",
    "Just around the corner": "Expected to happen very soon.",
    "Just coming up to": "Used to indicate time approaching a specific hour, e.g., nine o'clock.",
    "Just deserts": "When a bad person gets the punishment they deserve.",
    "Just for the heck of it": "Doing something without a good reason.",
    "Just for the record": "Said to clarify something for information only.",
    "Just in the nick of time": "Doing something with seconds to spare.",
    "Just off the boat": "Naive and inexperienced.",
    "Just what the doctor ordered": "Exactly what was needed.",
    "Justice is blind": "Justice is impartial and objective.",
    "Kick up a row": "To start a fight or create disturbance.",
    "Keep ones eye on the ball": "Be ready or alert for something.",
    "Kangaroo court": "An unofficial or illegal court.",
    "Keep body and soul together": "To survive with just enough resources.",
    "Keep your eye on the ball": "Stay alert and pay attention.",
    "Know which way the wind blows": "Understand how things are developing.",
    "Loaves and fishes": "Actions done for material benefits.",
    "Like a shag on a rock": "Completely alone.",
    "Let someone slide": "To neglect or overlook something.",
    "Let the cat out of the bag": "To reveal a secret.",
    "Let nature take its course": "Allow events to unfold naturally.",
    "Like a sitting duck": "Totally unaware and vulnerable.",
    "Lion’s share": "The major portion.",
    "Left to your own devices": "Not controlled; free to act.",
    "Make castles in the air": "Have unrealistic hopes or plans.",
    "Make a bee line for": "Go directly toward something.",
    "Make ones bed and lie on it": "Accept the consequences of your actions.",
    "Meet ones waterloo": "Encounter one's final defeat.",
    "Monkey around": "To waste time.",
    "My hands are full": "I am busy.",
    "Make a dry face": "Show disappointment.",
    "Make a monkey of someone": "Make someone look foolish.",
    "Man of his word": "Someone who keeps promises.",
    "Many moons ago": "A long time ago.",
    "Nobody’s fool": "A self-sufficient person.",
    "Not having a leg to stand for": "Lacking proof or justification.",
    "Never-never land": "An ideal or imaginary place.",
    "No love lost between": "Mutual dislike.",
    "Needle in a haystack": "Something very hard or impossible to find.",
    "New brush sweeps clean": "A new perspective brings change.",
    "No smoke without fire": "Suspicion often has a basis in fact.",
    "Once in a blue moon": "Very rarely.",
    "On the bandwagon": "Doing something because others are doing it.",
    "Open Pandora’s box": "To inadvertently create more problems.",
    "Over the moon": "Extremely happy.",
    "On its last legs": "In bad condition and near the end.",
    "Old flames die hard": "It's very difficult to forget old things",
    "On pins and needles": "You are very worried about something",
    "On the carpet": "You are in trouble and have to explain yourself to a superior",
    "On the hook": "Responsible for something",
    "Only the wearer knows where the shoe pinches": "Only the person suffering knows how bad it is",
    "Pass muster": "To be approved",
    "Pick someone to pieces": "To criticize sharply",
    "Paper over the cracks": "To try to hide something wrong",
    "Put the cart before the horse": "Doing things in the wrong order",
    "Pull up the shocks": "To do things correctly",
    "Parrot fashion": "To learn word for word, without understanding",
    "Pay on the nail": "To pay promptly in cash",
    "Pen is mightier than the sword": "Words are more powerful than violence",
    "Pick someone’s brains": "To ask someone for advice or information",
    "Pieces of the same cake": "Things with the same qualities",
    "Play fast and loose": "To behave irresponsibly",
    "Poker face": "Expressionless face that reveals nothing",
    "Quarrel with bread and butter": "To risk one's livelihood by arguing with one's boss",
    "Quiet as a cat": "Making as little noise as possible",
    "Quiet as a mouse": "Absolutely silent",
    "Queer fish": "A strange or eccentric person",
    "Round the twist": "Go crazy",
    "Read between the lines": "Understand hidden meanings",
    "Rack and ruin": "To be destroyed or fall apart",
    "Rain on your parade": "To spoil someone's plans",
    "Rake someone over the coals": "To scold or criticize severely",
    "Recipe for disaster": "A situation likely to lead to trouble",
    "Red carpet": "Special treatment for someone important",
    "Red herring": "Something that distracts from the real issue",
    "Red letter day": "A day of special significance or luck",
    "Reduce to ashes": "Completely destroyed or ruined",
    "Round the houses": "Taking an unnecessarily long route",
    "Rub shoulders": "To meet and spend time with people, especially famous or powerful",
    "Run into the sand": "To fail to achieve a result",
    "Salt on the earth": "Fundamentally good people",
    "Sands of time": "Tiny passing amounts of time",
    "Shake a leg": "To hurry up",
    "Spill the beans": "To expose a secret",
    "Snake in the grass": "A hidden enemy",
    "Snake in the shoes": "To be in a state of fear",
    "Stood to his guns": "Maintained one's opinion",
    "Showing the door": "Asking someone to leave",
    "Song and a dance": "An excuse or elaborate story",
    "Salad days": "A happy period in one’s youth",
    "Sail under false colors": "To deceive by pretending to be something else",
    "Threaded his way out": "Walked carefully through",
    "Take the cloth": "To become a priest",
    "Talk turkey": "To discuss seriously and solve problems",
    "Tit for tat": "Retaliation in equal measure",
    "To crow over": "To triumph over someone",
    "To blow a fuse": "To become very angry",
    "Though thick and thin": "In good times and bad",
    "To bell the cat": "To take a great risk",
    "To look through colored glasses": "To see things with bias",
    "Taking to a brick wall": "Talking without receiving a response",
    "Turned a deaf ear": "Ignored or refused to listen",
    "Take a back seat": "To reduce one's involvement",
    "Tables are turned": "Situation has reversed giving advantage to the previously disadvantaged",
    "Take someone under your wing": "To protect or mentor someone",
    "Take your medicine": "Accept the consequences of one's actions",
    "Talking to a brick wall": "Talking with no response",
    "Taste of your own medicine": "Receive the same bad treatment one has given others",
    "The apple does not fall far from the tree": "Children resemble their parents",
    "Upset the apple cart": "To create problems or difficulties",
    "Under a cloud": "Suspected of wrongdoing",
    "Under fire": "Criticized heavily",
    "Under your nose": "Happening right in front of you",
    "Up for grabs": "Available to anyone who can take it",
    "Up to the neck": "Heavily involved in something",
    "Up a river without a paddle": "In a bad situation without a solution",
    "Uncharted waters": "New and unknown situation",
    "Under lock and key": "Stored securely",
    "Vale of tears": "This world and its suffering",
    "Velvet glove": "Gentle appearance but tough inside",
    "Vent your spleen": "Release anger",
    "Vicar of Bray": "Changes beliefs for personal gain",
    "Vicious circle": "A sequence that worsens itself continuously",
    "Vinegar tits": "A mean-spirited, unloving woman",
    "Virgin territory": "Unexplored area",
    "Voice in the wilderness": "An unheeded warning or opinion",
    "Volte-face": "A complete reversal of position",
    "Vultures are circling": "Danger is near and enemies are waiting",
    "Weight one’s word": "Be careful about what one says",
    "Wait for a raindrop in the drought": "Waiting for something extremely unlikely",
    "Walking on broken glass": "When a person is punished for something",
    "Wet behind the ears": "Very young or inexperienced",
    "Whale of a time": "To really enjoy yourself",
    "Work your fingers to the bone": "To work extremely hard",
    "Wrench in the works": "Something that ruins a plan",
    "X factor": "Dangers for military personnel civilians don't face, for which they are paid",
    "X marks the spot": "Used to say where something is located or hidden",
    "X-rated": "Not suitable for children",
    "Yah boo sucks": "Expression of no sympathy with someone",
    "Yank my chain": "Telling someone to stop bothering you",
    "Yell bloody murder": "To protest angrily or scream in fear",
    "Yellow press": "Popular and sensationalist newspapers",
    "Yellow streak": "To be cowardly",
    "Yellow-bellied": "A coward",
    "Yen": "A desire to do something",
    "Yeoman's service": "To serve in an exemplary manner",
    "Yes-man": "Someone who always agrees with those in authority",
    "Yesterday's man or Yesterday's woman": "Someone whose career is over or in decline",
    "You are what you eat": "Good diet is key to good health",
    "You can catch more flies with honey than with vinegar": "Politeness is more effective than confrontation",
    "You can choose your friends, but you can't choose your family": "You have to make the best of the family you're born into",
    "You can lead a horse to water, but you can't make it drink": "You can offer help but can't force acceptance",
    "You can say that again": "Strong agreement with what was said",
    "You can't fight City Hall": "You can't change big institutions or bureaucracy",
    "You can't have cake and the topping, too": "You can't have it all, especially if contradictory",
    "You can't have your cake and eat it": "You can't have things both ways",
    "You can't hide elephants in mouse holes": "Big issues can't be hidden",
    "You can't make a silk purse out of a sow's ear": "You can't turn something bad into something good",
    "You can't make an omelette without breaking eggs": "To achieve something, sacrifices are often necessary",
    "You can't take it with you": "Enjoy life now because material things can't be taken after death",
    "You can't teach an old dog new tricks": "Hard to change habits of someone older",
    "You can't un-ring a bell": "Once done, actions can't be undone",
    "You could have knocked me down with a feather": "Extreme shock or surprise",
    "You do not get a dog and bark yourself": "Don't do the work of your subordinates",
    "You get what you pay for": "Cheap things often lack quality",
    "You reap what you sow": "Actions have consequences",
    "You said it!": "Complete agreement with a statement",
    "You scratch my back and I'll scratch yours": "Mutual benefit from helping each other",
    "You what?": "Surprise or disbelief at what was heard",
    "You're toast": "You are in a lot of trouble",
    "You've got rocks in your head": "Acted with a lack of intelligence",
    "You've made your bed- you'll have to lie in it": "Live with the consequences of your actions",
    "Young blood": "Young people with new ideas",
    "Young Turk": "A rebellious young person",
    "Your belly button is bigger than your stomach": "Taking on more than one can handle",
    "Your call": "Your decision to make",
    "Your name is mud": "You have a bad reputation",
    "Your sins will find you out": "Wrongdoings will eventually be exposed",
    "Zero hour": "The time when something important begins",
    "Zero tolerance": "No overlooking of any crime, however small",
    "Zigged before you zagged": "Did things in the wrong order",
    "Zip it": "Be quiet",
    "Zip your lip": "Shut up or keep quiet about something"
}